const tiles = [
  { id: 1, Board: true},
  { id: 2, Board: true},
  { id: 3, Board: true},
  { id: 4, Board: true},
  { id: 5, Board: true},
  { id: 6, Board: true},
  { id: 7, Board: true},
  { id: 8, Board: true},
  { id: 9, Board: true},
  { id: 10, Board:true},
  { id: 11, Board:true},
  { id: 12, Board:true},
  { id: 13, Board:true},
  { id: 14, Board:true},
  { id: 15, Board:true},
  { id: 16, Board:true},
  { id: 17, Board:true},
  { id: 18, Board:true},
  { id: 19, Board:true},
  { id: 20, Board:true},
  { id: 21, Board:true},
  { id: 22, Board:true},
  { id: 23, Board:true},
  { id: 24, Board:true},
  { id: 25, Board:true},
  { id: 26, Board:true},
  { id: 27, Board:true},
  { id: 28, Board:true},
  { id: 29, Board:true},
  { id: 30, Board:true},
  { id: 31, Board:true},
  { id: 32, Board:true},
  { id: 33, Board:true},
  { id: 34, Board:true},
  { id: 35, Board:true},
  { id: 36, Board:true},
  { id: 37, Board:true},
  { id: 38, Board:true},
  { id: 39, Board:true},
  { id: 40, Board:true},
  { id: 41, Board:true},
  { id: 42, Board:true},
  { id: 43, Board:true},
  { id: 44, Board:true},
  { id: 45, Board:true},
  { id: 46, Board:true},
  { id: 47, Board:true},
  { id: 48, Board:true},
  { id: 49, Board:true}
]

export default tiles